### PR TITLE
ppcoin v0.5.2 merged

### PR DESCRIPTION
**Pull request by hrobeers**
Please review and consider merging.

I'm a unsure about [this line](https://github.com/hrobeers/Peershares/blob/merge-ppcoin-0.5.2/src/script.cpp#L1413) as Peershares seems to be the only codebase returning 1 here.

Please check following projects as a reference:
[Peershares master line 1410](https://github.com/Peershares/Peershares/blob/master/src/script.cpp#L1410)
[Peercoin line 1409](https://github.com/ppcoin/ppcoin/blob/master/src/script.cpp#L1409)
[Bitcoin 0.9 line 1476](https://github.com/bitcoin/bitcoin/blob/0.9/src/script.cpp#L1476)
[NuBits line 1354](https://bitbucket.org/JordanLeePeershares/nubit/src/cd6e9ee263579fc3e2cddd3cad1e6eef685112a5/src/script.cpp?at=master&fileviewer=file-view-default#script.cpp-1354)

Kind Regards,
hrobeers

### CODE REVIEW

**Comment by hrobeers** [comment]
I started the client, it couldn't find any nodes on the testnet.
But I didn't start a new chain yet.

I'll report on this later this week.

**Comment by randuev** [comment]
@brossi would you have time to merge this one? thank you!

**Comment by brossi** [comment]
@sigmike or @glv2 , would you mind taking a quick look at this PR before I merge it in? It looks like it's in good order, but the devil is in the details, and either of you are more qualified than I to review for "gotchas". Thanks!

**Comment by hrobeers** [comment]
You should be able to connect to 62.163.212.157:9090 using the code from my testnet branch: https://github.com/hrobeers/Peershares/tree/testnet

However, I believe the code is affected by the following bug: https://www.peercointalk.org/index.php?topic=4443.0
As I experience some issues with the amounts of shares displayed in the client.

Will update on this later, but have some other higher priority work to do.

**Comment by hrobeers** [comment]
I will merge the the recently released ppcoin 0.5.3
Fix the unit tests, like I did for ppcoin, hopefully sunny merges this soon.
And I'll open a new pull request.

**Pull request closed without merging**
